language: go
sudo: false

notifications:
  webhooks:
    # this URL can be found at gitter.im by clicking
    # Settings -> Integrations -> Travis
    urls:
      - https://webhooks.gitter.im/e/a2c9aec0adb49d0111e4
    on_success: change
    on_failure: always
    on_start: never

go:
  - 1.5.4
  - 1.6.2

services:
  - postgresql

before_script:
  - psql -c "create user ghenga with encrypted password 'ghenga'" -U postgres
  - psql -c "create database ghenga with owner ghenga" -U postgres

install:
  - go version
  - export GOBIN="$GOPATH/bin"
  - export PATH="$PATH:$GOBIN"
  - go get github.com/constabulary/gb/...
  - go get -u github.com/golang/lint/golint
  - go get golang.org/x/tools/cmd/goimports
  - gb info

script:
  - gb build
  - GHENGA_TEST_DB="host=localhost user=ghenga password=ghenga dbname=ghenga" gb test
  - diff <(GOPATH="$PWD:$PWD/vendor" goimports -d ./src) <(printf "")
  - diff <(golint ./src/...) <(printf "")
